name: CI - Validação de Código

on:
  push:
    branches: [ develop, test, staging, main ]
  pull_request:
<<<<<<< HEAD
    branches: [ develop ]
=======
    branches: [ develop, test, staging, main ]
>>>>>>> origin/staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar Lint
        run: npm run lint

      - name: Verificar Build
        run: npm run build